### ISSUE TITLE
demos\interactive list issues

### ISSUE THREAD

**Issue by VinceJnz** [vecty-material/material#51]
not working

```
13:03:51.032 panic: runtime error: invalid memory address or nil pointer dereference
13:03:51.034 [signal 0xb code=0x5c7268 addr=0x17130029 pc=0x0]
13:03:51.035 <empty string>
13:03:51.035 goroutine 6 [running]: 
13:03:51.035 github.com/hexops/vecty.(*HTML).reconcileProperties.func1(0x730b8, 0x662460, 0x662440, 0x1, 0x1, 0x18420, 0x4e078) 
13:03:51.035 	D:/Users/Vince/Documents/Go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:246 +0x11 
13:03:51.036 github.com/hexops/vecty.funcOf.func1(0x7ff8000100001328, 0x660210, 0x662430, 0x1, 0x1, 0x660218, 0x27a00) 
13:03:51.036 	D:/Users/Vince/Documents/Go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom_js.go:60 +0x15 
13:03:51.036 syscall/js.handleEvent() 
13:03:51.036 	C:/Program Files/Go/src/syscall/js/func.go:96 +0x24 
13:03:51.037 exit code: 2
```

**Comment by xoviat** [comment]
sorry; I seem to have missed this.
